package CSE101;

public class Lecture06 {
    public static void main(String[] args) {
        // DEFINING METHODS
        /**
         * public static int methodName(int num1, double num2){
         *    1     2     3     4        5a  5b     6a    6b
         * }
         *    1 and 2 (pubic and static) are modifiers
         *    3 (int) return value type if there is no return; 'void' is used instead
         *    4 name of the method
         *    5 and 6 parameters (the parameters defined in the method headers are called formal parameters)
         *    4, 5 and 6 method signature
         *    1 to 6b is header
         *    and between braces is body
         *
         *
         *    Formal Parameters: The parameters defined in the method headers are known as formal parameters
         *    Actual Parameters: The parameters specified when called (or invoked) are known as actual paramethers or arguments
         */

        //in java, unlike in python, methods can be defined before or after called...
        // to call a method from another class, use;
        //ClassName.methodName()


        //GENERATING RANDOM CHARACTERS
        /**
         * All chars have a hexadecimal value between 0 and FFFF or decimal value between 0 and 65535.
         * So we can obtain a random char using Math.random() method..
         */
        char ch = (char) ((int)(Math.random()*65536));
        System.out.println(ch);
        /**
         * or we can obtain a lowercase alphabetic char using:
         */
        char ch1 = (char) ((((int)'z'-(int)'a'+1))*Math.random()+'a');
        System.out.println(ch1);
        // Any char between c1 and c2 could be generated by:
        //char ch = (char) (ch1+Math.random()*(ch2-c1+1))
    }
}
